--- #YAML:1.0
name:               Business-OnlinePayment-USAePay
version:            0.02
abstract:           ~
author:
    - Jeff Finucane <jeff@cmh.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Business::CreditCard:  0.27
    Business::OnlinePayment:  3
    Business::OnlinePayment::HTTPS:  0.04
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
